services:
  - type: web
    name: library-management-backend
    env: docker
    region: virginia
    plan: free
    branch: Myles
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: change-me-in-render
      - key: DATABASE_URI
        value: sqlite:///instance/library.db
      - key: FRONTEND_ORIGINS
        value: "http://localhost:5173,http://localhost:5174,http://localhost:5175,http://localhost:5176,http://localhost:5177,http://localhost:5178,http://127.0.0.1:5173,http://127.0.0.1:5174,http://127.0.0.1:5175,http://127.0.0.1:5176,http://127.0.0.1:5177,http://127.0.0.1:5178,https://library-management-system-frontend-en0q.onrender.com,https://library-management-system-frontend-jade.vercel.app"
